<a href="https://colab.research.google.com/github/bhaskarchaithra06-coder/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array-> collection of data with same datatype(homogenious)

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a=np.array([1,2,3,0,4])
a

array([1, 2, 3, 0, 4])

In [ ]:
a=np.array([1,2,3,0,4,"a"])
print(a)

['1' '2' '3' '0' '4' 'a']


In [ ]:
#slicing

1#forward slicing
2#backward slicing

b=np.array([1,2,3,4,5])

#print1,2
#print 5,4
#print 4,5
#print 2,3

print(b[0:2])
print(b[-1:-3:-1])
print(b[3:])
print(b[-4::-1])


[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimensions

a=np.array([1,2,3,4,5])
b=np.array([[1,2],[3,4]])

a.ndim #dimension=1 vector

b.ndim #dimension=2 matrix
print(b)


[[1 2]
 [3 4]]


In [ ]:
#create a 2*2 matrix 2,3,4,5

z=np.array([[2,3],[4,5]])
print(z)

print(z.shape)

print(z.ndim)

print(z.size) #it is used to know total number of elements in a matrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#create a 2x3 matrix and print  ,size,shape,dimension
z=np.array([[2,3],[3,4],[5,4]])
print(z)
print(z.size)
print(z.shape)
print(z.ndim)

[[2 3]
 [3 4]
 [5 4]]
6
(3, 2)
2


In [ ]:
#create a 4x2 matrix its size shape dimensions
z=np.array([[1,2],[3,4],[5,6],[7,8]])
print(z)
print(z.size)
print(z.shape)
print(z.ndim)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]
8
(4, 2)
2


In [ ]:
#create a 4x4 matrix display its size,shape dimensions
import numpy as np
z=np.array([[1,2,3,4],[5,3,2,2],[7,6,5,3],[3,4,3,2]])
print(z)
print(z.size)
print(z.shape)
print(z.ndim)


[[1 2 3 4]
 [5 3 2 2]
 [7 6 5 3]
 [3 4 3 2]]
16
(4, 4)
2


In [ ]:
#19/9/2025

In [ ]:

z[0] #to get the first row
z[:,0]
z[1,1]
z[2,2]
z[3,2:]
z[2:,2:]
z[2:,1:3]
z[1:3,3]
z[1:3,0:3]
z[0:3,1:]
z[0:,1]
z[0:,0:]



array([[1, 2, 3, 4],
       [5, 3, 2, 2],
       [7, 6, 5, 3],
       [3, 4, 3, 2]])

In [ ]:
#zero matrix-->all the matrix are zero

z=np.zeros([3,3,3],dtype=complex)
z


array([[[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]],

       [[0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j]]])

In [ ]:
z=np.zeros([2,3,3],dtype=int)
z

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:
#one matrix

z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create two 2x2 matrix
z=np.array([[1,2],[3,4]])
b=np.array([[3,2],[6,7]])
print(z)
print(b)

[[1 2]
 [3 4]]
[[3 2]
 [6 7]]


In [ ]:
#matrix addition

print(z+b)

#matrix substraction

print(z-b)

#matrix multiplication

print(z*b) #not a matrix multiplication

print(z@b) #matrix multiplication

print(z.dot(b)) #matrix multiplication

#matrix division

print(z/b)

#magic-->_add_ the functions that starts with


[[ 4  4]
 [ 9 11]]
[[-2  0]
 [-3 -3]]
[[ 3  4]
 [18 28]]
[[15 16]
 [33 34]]
[[15 16]
 [33 34]]
[[0.33333333 1.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix

z=np.full([3,3],7,dtype=int)
z

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
#create a 3x4 matrix with value 9 and datatype complex

z=np.full([3,4],9,dtype=complex)
z

array([[9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j],
       [9.+0.j, 9.+0.j, 9.+0.j, 9.+0.j]])

In [ ]:
#identity matrix--

z=np.identity(3,dtype=int)
z

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
z=np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#create a 4x4 matrix

z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z)
print(z.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=z.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
#range

a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange

a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values

a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.2,3.6,3.4]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.2, 3.6, 3.4]])

In [ ]:
#floor

z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 3., 3.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 4., 4.]])

In [ ]:
#round

z=np.round(a)
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 4., 3.]])

In [5]:
#create a 3x3 matrix
import numpy as np


a=np.arange(1,10).reshape(3,3)
print(a)

a.max()

a.max(axis=1)

a.max(axis=0)

a.min()

a.min(axis=1)

a.min(axis=0)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

In [ ]:
#22/09/2025
#Monday

In [6]:
#create a 3x3 matrix
import numpy as np

a=np.arange(1,10).reshape(3,3)
print(a)

a.max()

a.max(axis=1)

a.max(axis=0)

a.min()

a.min(axis=1)

a.min(axis=0)

a.sum()

a.sum(axis=1)

a.sum(axis=0)

+np.sqrt(a)
+np.sin(a)
+np.cos(a)
+np.tan(a)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [7]:
a.flatten()


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#sort
#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,2],[6,9,8]])
print(a)
b=np.sort(a,axis=0)
b

[[3 4 1]
 [5 3 2]
 [6 9 8]]


array([[3, 3, 1],
       [5, 4, 2],
       [6, 9, 8]])

In [12]:
#sort
#create a 3x3 matrix

a=np.array([[3,4,1],[5,3,2],[6,9,8]])
print(a)
b=np.sort(a,axis=0)
print(b)
c=np.argsort(a,axis=1)
print(c)

[[3 4 1]
 [5 3 2]
 [6 9 8]]
[[3 3 1]
 [5 4 2]
 [6 9 8]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
